# Generated by Django 2.0.5 on 2019-05-06 22:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('user', 'text')},
        ),
    ]
