# Generated by Django 2.0.5 on 2019-05-08 07:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_auto_20190508_1239'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('text', 'user')},
        ),
    ]
