# Generated by Django 2.0.5 on 2019-05-08 23:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20190509_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
